     f"  k1 = {info['distortion_coefficients']['k1']:.6f}",
        f"  k2 = {info['distortion_coefficients']['k2']:.6f}",
        f"  p1 = {info['distortion_coefficients']['p1']:.6f}",
        f"  p2 = {info['distortion_coefficients']['p2']:.6f}",
        f"  k3 = {info['distortion_coefficients']['k3']:.6f}",
